Hotfix the npm download ERR_SOCKET_TIMEOUT issue (#infra)
By this hotfix we will have an ugly but working solution to the
ERR_SOCKET_TIMEOUT issue when npm downloads packages. This issue happens to us
in about a 50% of calls which is too much for the CI.

This should be a hotfix for all our CI and we should ideally have a correct
solution to this in the future, if we will be able to find some...

diff --git a/ui/webui/Makefile.am b/ui/webui/Makefile.am
--- a/ui/webui/Makefile.am
+++ b/ui/webui/Makefile.am
@@ -87,5 +87,25 @@ test/common:
 
 $(NODE_MODULES_TEST): package.json
 	rm -f package-lock.json #  if it exists already, npm install won't update it; force that so that we always get up-to-date packages
-	env -u NODE_ENV npm install #  unset NODE_ENV, skips devDependencies otherwise
+# unset NODE_ENV for npm install call to avoid skiping of devDependencies
+# this below is an ugly and awful workaround for "npm ERR! code ERR_SOCKET_TIMEOUT" error which showed up in 50% of calls
+# TODO: find out proper fix instead of this workaround
+	TMPFILE="./npm-install.log"; \
+	COUNTER=1; \
+	while true; do \
+		rm -f $$TMPFILE; \
+		env -u NODE_ENV npm install 2>&1 | tee $$TMPFILE; \
+		if [ "$$COUNTER" -eq 6 ]; then \
+			echo "npm download was not successful after $$(expr $$COUNTER - 1) retries!"; \
+			rm -f $$TMPFILE; \
+			exit 1; \
+		fi; \
+		if grep -q "npm ERR! code ERR_SOCKET_TIMEOUT" $$TMPFILE; then \
+			echo "$$COUNTER retry of npm download"; \
+			((COUNTER++)); \
+			continue; \
+		fi; \
+	break; \
+	done; \
+	rm -f $$TMPFILE
 	env -u NODE_ENV npm prune
